"""auto update

Revision ID: b0a1e31d3ce1
Revises: ed11ce086d83
Create Date: 2026-03-02 05:19:26.940745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a1e31d3ce1'
down_revision: Union[str, Sequence[str], None] = 'ed11ce086d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('products', 'image_url_2')
    op.drop_column('products', 'original_price')
    op.drop_column('products', 'image_url_3')
    op.drop_column('products', 'short_description')
    op.drop_column('products', 'features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('features', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('image_url_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('original_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('image_url_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'created_at')
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.drop_table('support_messages')
    # ### end Alembic commands ###